### ISSUE TITLE
Array.isArray

### ISSUE THREAD

**Issue by dov-yih** [yidafu/notes#3]
[Determining with absolute accuracy whether or not a JavaScript object is an array](http://web.mit.edu/jwalden/www/isArray.html)

**Comment by yidafu** [comment]
Array.isArray() 本质上检测的是对象的 `[[Class]]`值，`[[Class]]`是对象的一个内部属性，里面包含了对象的类型信息，其格式为 `[object Xxx]` ，`Xxx` 就是对应的具体类型 。对于数组而言，`[[Class]]` 的值就是 `[object Array]` 。
